Repository neumannd/pytest_fun, pull requests merged in 2020-04, with the labels that each got.

#7 updated readme with conda installation
  Readme.md
Labels: documentation

#8 added simple tests
  pytest_fun/test/test_simple.py
Labels: enhancement

#14 removed usage of versioneer; fixed #13
  pytest_fun/_version.py
  versioneer.py
Labels: enhancement

#18 removed versioneer dependencies in setup files; fixed #13
  setup.cfg
  setup.py
Labels: bug

#17 Pytest marks def
  pytest.ini
  tests/test_with_decorators.py
Labels: enhancement

#27 added link + keywords to IOOS Compliance Checker testing; fixed #12
  Readme.md
Labels: documentation

#29 added introduction, examples to Readme.md
  Readme.md
Labels: documentation

#25 added tests with xfail and skip; fixed #22; fixed #11
  tests/test_with_decorators.py
Labels: enhancement

#28 added mock links
  Readme.md
Labels: documentation

#34 rename one test_add_true fun; fixed #33
  tests/test_with_decorators.py
Labels: bug

#39 two new markers; fixed #38
  pytest.ini
  tests/test_with_decorators.py
  tests/test_with_fixtures.py
Labels: enhancement
